Config:
  # Neo4j URL with port number
  neo4j_uri: "neo4j://127.0.0.1:7687"
  # Neo4j user name, default is neo4j
  neo4j_user: neo4j
  # Password for Neo4j user
  neo4j_password: "password"
  # Elastic search host name or IP, without trailing slash
  es_host: localhost:9200
  # Path to about file
  about_file: config/searchablePagesContent.yaml

  model_files:
    - c3dc-model/model-desc/c3dc-model-props.yml
    - c3dc-model/model-desc/c3dc-model.yml

  prop_file: config/props-c3dc.yml
