Config:
  # Neo4j URL with port number
  neo4j_uri: "bolt://127.0.0.1:7687"
  # Neo4j user name, default is neo4j
  neo4j_user: neo4j
  # Password for Neo4j user
  neo4j_password: neo4j_password
  # Elastic search host name or IP, without trailing slash
  es_host: localhost