Properties:
  domain: popsci.cancer.gov
  rel_prop_delimiter: "$"

  plurals:
    breast_case: breast_cases
    breast_diag: breast_diags
    colo_case: colo_cases
    colo_diag: colo_diags
    colo_screen: colo_screens
    colo_treat: colo_treats
    cohort: cohorts
    demo: demos
    lung_case: lung_cases
    lung_diag: lung_diags
    lung_screen: lung_screens
    lung_treat: lung_treats
    ovar_case: ovar_cases
    ovar_diag: ovar_diags
    ovar_screen: ovar_screens
    ovar_treat: ovar_treats
    pros_case: pros_cases
    pros_diag: pros_diags
    pros_screen: pros_screens
    pros_treat: pros_treats
    visit: visits


  type_mapping:
    string: String
    number: Float
    integer: Int
    boolean: Boolean
    array: Array
    list: Array
    object: Object
    datetime: DateTime
    date: Date
    TBD: String

  id_fields:
    breast_case: breast_case_id
    breast_diag: breast_diag_id
    breast_elig: breast_elig_id
    breast_exit: breast_exit_id
    breast_hist: breast_hist_id
    breast_mort: breast_mort_id
    breast_regn: breast_regn_id
    clinical_trial: clinical_trial_id
    cohort: cohort_id
    colo_case: colo_case_id
    colo_diag: colo_diag_id
    colo_elig: colo_elig_id
    colo_exit: colo_exit_id
    colo_hist: surg_biopsy
    colo_mort: colo_mort_id
    colo_regn: colo_regn_id
    colo_screen: colo_screen_id
    colo_treat: colo_treat_id
    comp: comp_id
    demo: demo_id
    dhq: dhq_id
    dqx: dqx_id
    fem_health_cond: fem_health_cond_id
    health_cond: health_cond_id
    lung_case: lung_case_id
    lung_diag: lung_diag_id
    lung_elig: lung_elig_id
    lung_exit: lung_exit_id
    lung_hist: lung_hist_id
    lung_mort: lung_mort_id
    lung_regn: lung_regn_id
    lung_screen: lung_screen_id
    lung_treat: lung_treat_id
    male_health_cond: male_health_id
    mort: mort_id
    nsaid_use: nsaid_use_id
    ovar_case: ovar_case_id
    ovar_diag: ovar_diag_id
    ovar_elig: ovar_elig_id
    ovar_exit: ovar_exit_id
    ovar_hist: ovar_hist_id
    ovar_mort: ovar_mort_id
    ovar_regn: ovar_regn_id
    ovar_screen: ovar_screen_id
    ovar_treat: ovar_treat_id
    pros_case: pros_case_id
    pros_diag: pros_diag_id
    pros_elig: pros_elig_id
    pros_exit: pros_exit_id
    pros_hist: pros_hist_id
    pros_mort: pros_mort_id
    pros_regn: pros_regn_id
    pros_screen: pros_screen_id
    pros_treat: pros_treat_id
    risk: risk_id
    sqx: sqx_id
    visit: visit_id