Properties:
  domain: c3dc.cancer.gov
  rel_prop_delimiter: "$"

  plurals:
    diagnosis: diagnoses
    participant: participants
    sample: samples
    study: studies
    survival: survivals
    reference_file: reference_files

  type_mapping:
    list: String
    string: String
    number: Float
    integer: Int
    boolean: Boolean
    array: Array
    object: Object
    datetime: DateTime
    date: Date
    TBD: String

  id_fields:
    diagnosis: diagnosis_id
    participant: participant_id
    reference_file: reference_file_id
    sample: sample_id
    study: study_id
    survival: survival_id